/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.68
 * Generated at: 2023-04-10 05:51:30 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.WEB_002dINF.views.board;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class board_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(2);
    _jspx_dependants.put("/WEB-INF/lib/jstl-1.2.jar", Long.valueOf(1669273540242L));
    _jspx_dependants.put("jar:file:/Users/minsoo/Desktop/team/.metadata/.plugins/org.eclipse.wst.server.core/tmp0/wtpwebapps/sns_damso/WEB-INF/lib/jstl-1.2.jar!/META-INF/c.tld", Long.valueOf(1153352682000L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSP들은 오직 GET, POST 또는 HEAD 메소드만을 허용합니다. Jasper는 OPTIONS 메소드 또한 허용합니다.");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html;charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write('\n');
      out.write('\n');
      out.write('\n');
      org.apache.jasper.runtime.JspRuntimeLibrary.include(request, response, "../layout/header.jsp", out, false);
      out.write("\n");
      out.write("<link\n");
      out.write("		href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/resources/css/styleBoard_230405.css\"\n");
      out.write("		rel=\"stylesheet\">\n");
      out.write("\n");
      out.write("<style>\n");
      out.write("	a {\n");
      out.write("		cursor: pointer;\n");
      out.write("	}\n");
      out.write("	.feed-main {\n");
      out.write("		display :flex;\n");
      out.write("		justify-content: center;\n");
      out.write("	}\n");
      out.write("	.myfeed {\n");
      out.write("		max-width: 620px;\n");
      out.write("	}\n");
      out.write("	.story {\n");
      out.write("		height: auto;\n");
      out.write("		display: flex;\n");
      out.write("		padding: 45px 0 20px;\n");
      out.write("		justify-content: space-around;\n");
      out.write("	}\n");
      out.write("	.myinfo {\n");
      out.write("		width: 250px;\n");
      out.write("		height: 400px;\n");
      out.write("	}\n");
      out.write("	.story-img, .media .info-img {\n");
      out.write("		width: 60px;\n");
      out.write("		height: 60px;\n");
      out.write("		border-radius: 50%;\n");
      out.write("		border: white 2px solid;\n");
      out.write("		padding: 0;\n");
      out.write("	}\n");
      out.write("	.story-active {\n");
      out.write("		width: 64px;\n");
      out.write("		height: 64px;\n");
      out.write("		border-radius: 50%;\n");
      out.write("		border: #cceabf 2px solid;\n");
      out.write("	}\n");
      out.write("	.myboard {\n");
      out.write("		width : 470px;\n");
      out.write("		margin: auto;\n");
      out.write("		padding-top: 30px;\n");
      out.write("	}\n");
      out.write("	.board-btnbox {\n");
      out.write("		margin: 0;\n");
      out.write("		padding: 10px;\n");
      out.write("	}\n");
      out.write("	.board-btnbox li {\n");
      out.write("		padding-right: 8px;\n");
      out.write("	}\n");
      out.write("	.board-btnbox li:nth-of-type(4) {\n");
      out.write("		float : right;\n");
      out.write("		padding-right: 0;\n");
      out.write("		margin-right: -23px;\n");
      out.write("	}\n");
      out.write("	.reply-view, .reply-add {\n");
      out.write("		color: #757575;\n");
      out.write("		font-size: 15px;\n");
      out.write("	}\n");
      out.write("	.reply-view p {\n");
      out.write("		padding: 5px 0 10px;\n");
      out.write("		margin:0;\n");
      out.write("	}\n");
      out.write("	.reply-add {\n");
      out.write("		border: none;\n");
      out.write("		width: 100%;\n");
      out.write("		margin-left: -2px;\n");
      out.write("		padding-bottom: 10px;\n");
      out.write("	}\n");
      out.write("	.feed-writer, .reply-view:hover, .feed-writer:hover {\n");
      out.write("		color: #fdb3b6;\n");
      out.write("	}\n");
      out.write("	.reply-addbtn {\n");
      out.write("		float: right;\n");
      out.write("		background-color: white;\n");
      out.write("		border: none;\n");
      out.write("		cursor: pointer;\n");
      out.write("		color: #757575;\n");
      out.write("	}\n");
      out.write("\n");
      out.write("</style>\n");
      out.write("\n");
      out.write("<div class=\"feed-main\">\n");
      out.write("\n");
      out.write("	<div class=\"myfeed\">\n");
      out.write("		<div class=\"story\">\n");
      out.write("			<div class=\"d-flex me-3\">\n");
      out.write("				<div class=\"story-active\">\n");
      out.write("					<a href=\"\">\n");
      out.write("						<img class=\"story-img\" src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/resources/img/attach.jpg\">\n");
      out.write("					</a>\n");
      out.write("				</div>\n");
      out.write("			</div>\n");
      out.write("			<div class=\"d-flex me-3\">\n");
      out.write("				<div class=\"story-active\">\n");
      out.write("					<a href=\"\">\n");
      out.write("						<img class=\"story-img\" src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/resources/img/attach.jpg\">\n");
      out.write("					</a>\n");
      out.write("				</div>\n");
      out.write("			</div>\n");
      out.write("			<div class=\"d-flex me-3\">\n");
      out.write("				<div class=\"story-active\">\n");
      out.write("					<a href=\"\">\n");
      out.write("						<img class=\"story-img\" src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/resources/img/attach.jpg\">\n");
      out.write("					</a>\n");
      out.write("				</div>\n");
      out.write("			</div>\n");
      out.write("			<div class=\"d-flex me-3\">\n");
      out.write("				<div class=\"story-active\">\n");
      out.write("					<a href=\"\">\n");
      out.write("						<img class=\"story-img\" src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/resources/img/attach.jpg\">\n");
      out.write("					</a>\n");
      out.write("				</div>\n");
      out.write("			</div>\n");
      out.write("			<div class=\"d-flex me-3\">\n");
      out.write("				<div class=\"story-active\">\n");
      out.write("					<a href=\"\">\n");
      out.write("						<img class=\"story-img\" src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/resources/img/attach.jpg\">\n");
      out.write("					</a>\n");
      out.write("				</div>\n");
      out.write("			</div>\n");
      out.write("			<div class=\"d-flex me-3\">\n");
      out.write("				<div class=\"story-active\">\n");
      out.write("					<a href=\"\">\n");
      out.write("						<img class=\"story-img\" src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/resources/img/attach.jpg\">\n");
      out.write("					</a>\n");
      out.write("				</div>\n");
      out.write("			</div>\n");
      out.write("			<div class=\"d-flex me-3\">\n");
      out.write("				<div class=\"story-active\">\n");
      out.write("					<a href=\"\">\n");
      out.write("						<img class=\"story-img\" src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/resources/img/attach.jpg\">\n");
      out.write("					</a>\n");
      out.write("				</div>\n");
      out.write("			</div>\n");
      out.write("			<div class=\"d-flex me-3\">\n");
      out.write("				<div class=\"story-active\">\n");
      out.write("					<a href=\"\">\n");
      out.write("						<img class=\"story-img\" src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/resources/img/attach.jpg\">\n");
      out.write("					</a>\n");
      out.write("				</div>\n");
      out.write("			</div>\n");
      out.write("\n");
      out.write("		</div>\n");
      out.write("\n");
      out.write("		<div class=\"boards\">\n");
      out.write("\n");
      out.write("		</div>\n");
      out.write("\n");
      out.write("	</div>\n");
      out.write("\n");
      out.write("	<div class=\"modal fade\" id=\"boardModal\" tabindex=\"-1\" role=\"dialog\" aria-labelledby=\"myModalLabel\"\n");
      out.write("		 aria-hidden=\"true\">\n");
      out.write("		<div class=\"modal-dialog modal-dialog-centered modal-lg\" role=\"document\">\n");
      out.write("			<div class=\"modal-content d-inline-block\">\n");
      out.write("				<div class=\"col-7 d-inline-block\">\n");
      out.write("					<img class=\"img-fluid\"\n");
      out.write("						 src=\"../../../resources/img/attach.jpg\"\n");
      out.write("						 alt=\"Image\" style=\"width:100%; max-height:587.5px\">\n");
      out.write("				</div>\n");
      out.write("\n");
      out.write("				<div class=\"col-3 d-inline-block\">\n");
      out.write("					<div id=\"user\">\n");
      out.write("						<div id=\"writer\" class=\"d-block\"></div>\n");
      out.write("						<div id=\"content\" class=\"d-block\"></div>\n");
      out.write("					</div>\n");
      out.write("					<div class=\"card\" style=\"width:300px\">\n");
      out.write("						<div class=\"card-body\" style=\"width:300px\">\n");
      out.write("		                   <ul class=\"list-group chat\">\n");
      out.write("			                <li class=\"list-group-item\" style=\"border:0px solid\"></li>\n");
      out.write("		                   </ul> \n");
      out.write("		                </div>\n");
      out.write("	                </div>\n");
      out.write("				</div>\n");
      out.write("			</div>\n");
      out.write("		</div>\n");
      out.write("	</div>\n");
      out.write("\n");
      out.write("	<div class=\"myinfo myinfo_moblie\">\n");
      out.write("		<div class=\"cardbox-header p-5 ms-3\">\n");
      out.write("			<div class=\"media\">\n");
      out.write("				<div class=\"d-flex me-3\">\n");
      out.write("					<a href=\"\">\n");
      out.write("						<img class=\"info-img\" src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/resources/img/attach.jpg\">\n");
      out.write("					</a>\n");
      out.write("				</div>\n");
      out.write("				<div class=\"media-body\">\n");
      out.write("					<p class=\"m-0\" style=\"font-weight: 600\">");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${member.email}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("</p>\n");
      out.write("					<p class=\"m-0\">");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${member.id}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("</p>\n");
      out.write("					<a href=\"/member/login\" style=\"font-size:10px;\">로그아웃</a>\n");
      out.write("				</div>\n");
      out.write("			</div>\n");
      out.write("		</div>\n");
      out.write("	</div>\n");
      out.write("</div>\n");
      out.write("<script> cp = '");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("'</script>\n");
      out.write("<script src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/resources/js/board.js\"></script>\n");
      out.write("<script src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/resources/js/reply.js\"></script>\n");
      out.write("<script>\n");
      out.write("	$(function () {\n");
      out.write("		moment.locale('ko')\n");
      out.write("		let str = \"\";\n");
      out.write("		var rno = '");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${reply.rno}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("';\n");
      out.write("		\n");
      out.write("		boardService.getList({categoty : 1}, function (result) {\n");
      out.write("			console.log(result)\n");
      out.write("			for (let i in result) {\n");
      out.write("				str += getBoardLiStr(result[i])\n");
      out.write("			}\n");
      out.write("			$(\".boards\").html(str)\n");
      out.write("		});\n");
      out.write("		\n");
      out.write("\n");
      out.write("		$(\".boards\").on(\"click\", \"div\", function () {\n");
      out.write("			boardService.get($(this).data(\"bno\"), function (result) {\n");
      out.write("				$(\"#boardModal\").modal(\"show\").data(\"bno\", result.bno)\n");
      out.write("				$(\"#writer\").text(result.writer)\n");
      out.write("				$(\"#content\").text(result.content)\n");
      out.write("				$(\"#regdate\").text(moment(result.regdate).startOf('day').fromNow())\n");
      out.write("				$(\"#modalFooter button\").show()\n");
      out.write("				$(\"#modalFooter button\").eq(2).hide()\n");
      out.write("				$(\"#boardModal\").modal(\"show\").data(\"bno\", result.bno)\n");
      out.write("				replyService.getList({bno:$(\"#boardModal\").modal(\"show\").data(\"bno\"), rno:rno}, function(result) {\n");
      out.write("					var str = \"\";\n");
      out.write("					for(var i in result) {\n");
      out.write("						str += getReplyLiStr(result[i]);\n");
      out.write("					}\n");
      out.write("					$(\".chat\").html(str);\n");
      out.write("				})\n");
      out.write("			})\n");
      out.write("		});\n");
      out.write("\n");
      out.write("		$(window).scroll(function () {\n");
      out.write("			var scrollTop = $(window).scrollTop();\n");
      out.write("			var innerHeight = $(window).innerHeight();\n");
      out.write("			var scrollHeight = $('body').prop('scrollHeight');\n");
      out.write("			if (scrollTop + innerHeight >= scrollHeight) {\n");
      out.write("				boardService.getList({bno : $(\".myboard:last\").data(\"bno\")}, function (result) {\n");
      out.write("					str = \"\"\n");
      out.write("					for (let i in result) {\n");
      out.write("						str += getBoardLiStr(result[i])\n");
      out.write("					}\n");
      out.write("					$(\".boards\").append(str)\n");
      out.write("				})\n");
      out.write("			}\n");
      out.write("		});\n");
      out.write("\n");
      out.write("		function getBoardLiStr(obj) {\n");
      out.write("			return `\n");
      out.write("			<div class=\"myboard\" data-bno=\"${obj.bno}\">\n");
      out.write("\n");
      out.write("				<div class=\"cardbox-header py-2\">\n");
      out.write("\n");
      out.write("					<div class=\"float-end\">\n");
      out.write("						<button class=\"btn btn-flat btn-flat-icon\" type=\"button\">\n");
      out.write("							<i class=\"fas fa-ellipsis-h\"></i>\n");
      out.write("						</button>\n");
      out.write("					</div>\n");
      out.write("\n");
      out.write("					<div class=\"media m-0\">\n");
      out.write("						<div class=\"d-flex mr-3\">\n");
      out.write("							<a href=\"\"><img class=\"img-fluid rounded-circle\"\n");
      out.write("											src=\"../../../resources/img/attach.jpg\"\n");
      out.write("											alt=\"User\"></a>\n");
      out.write("						</div>\n");
      out.write("						<div class=\"media-body\">\n");
      out.write("							<p class=\"m-0\">${obj.writer}</p>\n");
      out.write("							<small><span><i class=\"icon ion-md-pin\"></i>\n");
      out.write("								${obj.bno}</span></small> <small><span><i\n");
      out.write("								class=\"icon ion-md-time\"></i>${moment(obj.regdate).startOf('day').fromNow()}</span></small>\n");
      out.write("						</div>\n");
      out.write("					</div>\n");
      out.write("				</div>\n");
      out.write("				<div class=\"cardbox-item\">\n");
      out.write("					<img class=\"img-fluid\"\n");
      out.write("						 src=\"../../../resources/img/attach.jpg\"\n");
      out.write("						 alt=\"Image\" style=\"width:100%; max-height:587.5px\">\n");
      out.write("				</div>\n");
      out.write("				<div class=\"cardbox-base\">\n");
      out.write("					<ul class=\"board-btnbox\">\n");
      out.write("						<li><a><i class=\"far fa-heart\"></i></a></li>\n");
      out.write("						<li><a><i class=\"far fa-comment\"></i></a></li>\n");
      out.write("						<li><a><i class=\"far fa-paper-plane\"></i></a></li>\n");
      out.write("						<li><a><i class=\"far fa-bookmark\"></i></a></li>\n");
      out.write("					</ul>\n");
      out.write("					<div>\n");
      out.write("						<p style=\"margin-bottom:5px\">좋아요 ${obj.likecnt}개</p>\n");
      out.write("					</div>\n");
      out.write("					<div>\n");
      out.write("						<a class=\"feed-writer\">${obj.writer}</a><span class=\"board-content\" style=\"padding: 5px\">${obj.content}</span>\n");
      out.write("					</div>\n");
      out.write("					<div>\n");
      out.write("						<a class=\"reply-view\"><p>댓글 ${obj.replycnt}개 모두 보기</p></a>\n");
      out.write("						<input type=\"text\" class=\"reply-add\" placeholder=\"댓글 달기..\" />\n");
      out.write("					</div>\n");
      out.write("				</div>\n");
      out.write("			</div>\n");
      out.write("			`\n");
      out.write("		}\n");
      out.write("		\n");
      out.write("		function getReplyLiStr(obj) {\n");
      out.write("			return `<li class=\"list-group-item like\" data-rno=\"${obj.rno}\">\n");
      out.write("			   		<div class=\"header\">\n");
      out.write("						<strong class=\"primary-font\">${obj.writer}</strong>\n");
      out.write("						<small class=\"float-right text-muted\">${moment(obj.regdate).fromNow()}</small>\n");
      out.write("					</div>\n");
      out.write("					<div class=\"d-flex\">\n");
      out.write("					<span>${obj.content}</span>\n");
      out.write("					<a><i class=\"far far fa-heart\"></i></a></div>\n");
      out.write("					</li>`;\n");
      out.write("		}\n");
      out.write("		\n");
      out.write("		$('.like').click(function(){\n");
      out.write("			  if($('.far').hasClass('far fa-heart')) {\n");
      out.write("			    $('.far').removeClass('far fa-heart').addClass('fas fa-heart');\n");
      out.write("			  } else {\n");
      out.write("			    $('.far').removeClass('fas fa-heart').addClass('far fa-heart');\n");
      out.write("			  }\n");
      out.write("			})\n");
      out.write("		\n");
      out.write("		\n");
      out.write("		\n");
      out.write("		\n");
      out.write("	})\n");
      out.write("</script>\n");
      out.write("\n");
      out.write("\n");
      org.apache.jasper.runtime.JspRuntimeLibrary.include(request, response, "../layout/footer.jsp", out, false);
      out.write('\n');
      out.write('\n');
      out.write('\n');
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
